services:
  loadbalancer:
    image: loadbalancer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - loadbalancer
    ports:
      - "3000:3000"